FIELDS = {
    'TEXT_FIELDS' : [
        'Any Text Field',
        'Title',
        'Abstract',
        'Claims',
        'Inventor',
        'Owners',
        'Applicant',
        'IPC',
        'CPC',
        'PCT Filing No.',
        'Intl Pub No.'
    ],
    'INVENTOR_COUNTRIES' : [
        'abc'
    ],
    'STATUS' : [
        'All',
        'Active',
        'Patents',
        'Pending Applications',
        'Public Domain'
    ],
    'TYPES' : [
        'All Documents',
        'PCT',
        'Non-PCT'
    ],
    'LANGUAGES' : [
        'In Both Languages',
        'English',
        'French'
    ],
    'LICENSE_AVAILABILITY' : [
        'False',
        'True'
    ],
    'DATE_FIELDS' : [
        'Date Search Not Active',
        'Issue Date',
        'Filing Date',
        'Examination Request Date',
        'Open To Pub. Insp. Date',
        'Priority Date',
        'National Entry Date'
    ],
    'DATE_1' : "mm_dd_yy",
    'DATE_2' : "mm_dd_yy"
}

COUNTRIES = {
    'Afghanistan' : 'AF',
    'African Intellectual Property Organization (OAPI)' : 'OA',
    'African Regional Intellectual Property Organization (ARIPO)' : 'AP',
    'Albania' : 'AL',
    'Algeria' : 'DZ',
    'Andorra' : 'AD',
    'Angola' : 'AO',
    'Anguilla' : 'AI',
    'Antigua and Barbuda' : 'AG',
    'Argentina' : 'AR',
    'Armenia' : 'AM',
    'Aruba' : 'AW',
    'Australia' : 'AU',
    'Austria' : 'AT',
    'Azerbaijan' : 'AZ',
    'Bahamas' : 'BS',
    'Bahrain' : 'BH',
    'Bangladesh' : 'BD',
    'Barbados' : 'BB',
    'Belarus' : 'BY',
    'Belgium' : 'BE',
    'Belize' : 'BZ',
    'Benelux Office for Intellectual Property (BOIP)' : 'BX',
    'Benin' : 'BJ',
    'Bermuda' : 'BM',
    'Bhutan' : 'BT',
    'Bolivia, Plurinational State of' : 'BO',
    'Bonaire, Sint Eustatius and Saba' : 'BQ',
    'Bosnia and Herzegovina' : 'BA',
    'Botswana' : 'BW',
    'Bouvet Island' : 'BV',
    'Brazil' : 'BR',
    'Brunei Darussalam' : 'BN',
    'Bulgaria' : 'BG',
    'Burkina Faso' : 'HV',
    'Burma' : 'BU',
    'Burundi' : 'BI',
    'Cabo Verde' : 'CV',
    'Cambodia' : 'KH',
    'Cameroon' : 'CM',
    'Canada' : 'CA',
    'Cayman Islands' : 'KY',
    'Central African Republic' : 'CF',
    'Chad' : 'TD',
    'Chile' : 'CL',
    'China' : 'CN',
    'Colombia' : 'CO',
    'Community Plant Variety Office (European Union) (CPVO)' : 'QZ',
    'Comoros' : 'KM',
    'Congo' : 'CG',
    'Cook Islands' : 'CK',
    'Costa Rica' : 'CR',
    'Country Unknown' : 'ZZ',
    'Croatia' : 'HR',
    'Cuba' : 'CU',
    'Cyprus' : 'CY',
    'Czechoslovakia' : 'CS',
    'Czech Republic' : 'CZ',
    'Democratic People&#039;s Republic of Korea' : 'KP',
    'Democratic Republic of the Congo' : 'CD',
    'Denmark' : 'DK',
    'Djibouti' : 'DJ',
    'Dominica' : 'DM',
    'Dominican Republic' : 'DO',
    'Ecuador' : 'EC',
    'Egypt' : 'EG',
    'El Salvador' : 'SV',
    'Equatorial Guinea' : 'GQ',
    'Eritrea' : 'ER',
    'Estonia' : 'EE',
    'Ethiopia' : 'ET',
    'Eurasian Patent Organization (EAPO)' : 'EA',
    'European Patent Office (EPO)' : 'EP',
    'Falkland Islands (Malvinas)' : 'FK',
    'Faroe Islands' : 'FO',
    'Fiji' : 'FJ',
    'Finland' : 'FI',
    'France' : 'FR',
    'Gabon' : 'GA',
    'Gambia' : 'GM',
    'Georgia' : 'GE',
    'Germany' : 'DE',
    'Germany (Democratic Republic)' : 'DD',
    'Ghana' : 'GH',
    'Gibraltar' : 'GI',
    'Greece' : 'GR',
    'Greenland' : 'GL',
    'Grenada' : 'GD',
    'Guatemala' : 'GT',
    'Guernsey' : 'GG',
    'Guinea' : 'GN',
    'Guinea-Bissau' : 'GW',
    'Guyana' : 'GY',
    'Haiti' : 'HT',
    'Holy See' : 'VA',
    'Honduras' : 'HN',
    'Hungary' : 'HU',
    'Iceland' : 'IS',
    'India' : 'IN',
    'Indonesia' : 'ID',
    'International Bureau of the World Intellectual Property Org. (WIPO)' : 'IB',
    'Iran (Islamic Republic of)' : 'IR',
    'Iraq' : 'IQ',
    'Ireland' : 'IE',
    'Isle of Man' : 'IM',
    'Israel' : 'IL',
    'Italy' : 'IT',
    'Ivory Coast' : 'CI',
    'Jamaica' : 'JM',
    'Japan' : 'JP',
    'Jersey' : 'JE',
    'Jordan' : 'JO',
    'Kazakhstan' : 'KZ',
    'Kenya' : 'KE',
    'Kiribati' : 'KI',
    'Kuwait' : 'KW',
    'Kyrgyzstan' : 'KG',
    'Lao People&#039;s Democratic Republic' : 'LA',
    'Latvia' : 'LV',
    'Lebanon' : 'LB',
    'Lesotho' : 'LS',
    'Liberia' : 'LR',
    'Libya' : 'LY',
    'Liechtenstein' : 'LI',
    'Lithuania' : 'LT',
    'Luxembourg' : 'LU',
    'Macao' : 'MO',
    'Madagascar' : 'MG',
    'Malawi' : 'MW',
    'Malaysia' : 'MY',
    'Maldives' : 'MV',
    'Mali' : 'ML',
    'Malta' : 'MT',
    'Mauritania' : 'MR',
    'Mauritius' : 'MU',
    'Mexico' : 'MX',
    'Monaco' : 'MC',
    'Mongolia' : 'MN',
    'Montenegro' : 'ME',
    'Montserrat' : 'MS',
    'Morocco' : 'MA',
    'Mozambique' : 'MZ',
    'Myanmar' : 'MM',
    'Namibia' : 'NA',
    'Nauru' : 'NR',
    'Nepal' : 'NP',
    'Netherlands' : 'NL',
    'Netherlands Antilles' : 'AN',
    'New Caledonia' : 'NC',
    'New Zealand' : 'NZ',
    'Nicaragua' : 'NI',
    'Niger' : 'NE',
    'Nigeria' : 'NG',
    'Nordic Patent Institute (NPI)' : 'XN',
    'Northern Mariana Islands' : 'MP',
    'Norway' : 'NO',
    'Ofc. for Harmonization in the Internal Market (Trademarks and Designs)' : 'EM',
    'Oman' : 'OM',
    'Pakistan' : 'PK',
    'Palau' : 'PW',
    'Panama' : 'PA',
    'Papua New Guinea' : 'PG',
    'Paraguay' : 'PY',
    'Patent Ofc. of the Coop. Council for the Arab States of the Gulf (GCC)' : 'GC',
    'Peru' : 'PE',
    'Philippines' : 'PH',
    'Poland' : 'PL',
    'Portugal' : 'PT',
    'Qatar' : 'QA',
    'Republic of Korea' : 'KR',
    'Republic of Moldova' : 'MD',
    'Republic of the Marshall Islands' : 'MH',
    'Romania' : 'RO',
    'Russian Federation' : 'RU',
    'Rwanda' : 'RW',
    'Saint Helena' : 'SH',
    'Saint Kitts and Nevis' : 'KN',
    'Saint Lucia' : 'LC',
    'Saint Vincent and the Grenadines' : 'VC',
    'Samoa' : 'WS',
    'San Marino' : 'SM',
    'Sao Tome and Principe' : 'ST',
    'Saskatchewan' : 'S1',
    'Saudi Arabia' : 'SA',
    'Senegal' : 'SN',
    'Serbia' : 'RS',
    'Seychelles' : 'SC',
    'Sierra Leone' : 'SL',
    'Singapore' : 'SG',
    'Slovakia' : 'SK',
    'Slovenia' : 'SI',
    'Solomon Islands' : 'SB',
    'Somalia' : 'SO',
    'South Africa' : 'ZA',
    'South Georgia and the South Sandwich Islands' : 'GS',
    'South Sudan' : 'SS',
    'Spain' : 'ES',
    'Sri Lanka' : 'LK',
    'Sudan' : 'SD',
    'Suriname' : 'SR',
    'Swaziland' : 'SZ',
    'Sweden' : 'SE',
    'Switzerland' : 'CH',
    'Syrian Arab Republic' : 'SY',
    'Taiwan' : 'TW',
    'Tajikistan' : 'TJ',
    'Thailand' : 'TH',
    'The former Yugoslav Republic of Macedonia' : 'MK',
    'The Hong Kong Special Admin. Region of the People&#039;s Republic of China' : 'HK',
    'Timor-Leste' : 'TL',
    'Togo' : 'TG',
    'Tonga' : 'TO',
    'Trinidad and Tobago' : 'TT',
    'Tunisia' : 'TN',
    'Turkey' : 'TR',
    'Turkmenistan' : 'TM',
    'Turks and Caicos Islands' : 'TC',
    'Tuvalu' : 'TV',
    'Uganda' : 'UG',
    'Ukraine' : 'UA',
    'United Arab Emirates' : 'AE',
    'United Kingdom' : 'GB',
    'United Republic of Tanzania' : 'TZ',
    'United States of America' : 'US',
    'Uruguay' : 'UY',
    'USSR' : 'SU',
    'Uzbekistan' : 'UZ',
    'Vanuatu' : 'VU',
    'Venezuela, Bolivarian Republic of' : 'VE',
    'Viet Nam' : 'VN',
    'Virgin Islands (British)' : 'VG',
    'Western Sahara' : 'EH',
    'World Intellectual Property Organization (WIPO) (Intl. Bureau of)' : 'WO',
    'Yemen' : 'YE',
    'Yemen, Democratic' : 'YD',
    'Yugoslavia' : 'YU',
    'Zaire' : 'ZR',
    'Zambia' : 'ZM',
    'Zimbabwe' : 'ZW'
}